name: Deploy to FTP AwardSpace
run-name: ${{ github.actor }} FTP Deploy
on: push
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: Luis97lol/PSFTP@v1.4
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          pass: ${{ secrets.FTP_PASSWORD }}
