# name: Deploy to FTP AwardSpace
# on:
#   push:
#     branches:
#       - main

# jobs:
#   ftp-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: FTP Deploy
#       uses: w9jds/ftp-action@v1.0.2
#       with:
#         host: ${{ secrets.FTP_HOST }}
#         username: ${{ secrets.FTP_USERNAME }}
#         password: ${{ secrets.FTP_PASSWORD }}
#         localDir: ./ # Directorio a desplegar
#         remoteDir: /laravel/ # Ruta remota en el servidor
#         port: 21


on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: Penguibird/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.ftp_password }}
