# name: Deploy to FTP AwardSpace
# on:
#   push:
#     branches:
#       - main

# jobs:
#   ftp-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: FTP Deploy
#       uses: w9jds/ftp-action@v1.0.2
#       with:
#         host: ${{ secrets.FTP_HOST }}
#         username: ${{ secrets.FTP_USERNAME }}
#         password: ${{ secrets.FTP_PASSWORD }}
#         localDir: ./ # Directorio a desplegar
#         remoteDir: /laravel/ # Ruta remota en el servidor
#         port: 21


name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: genietim/ftp-action@releases/v4
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: "./laravel/"
